SQL> SELECT c.Customer_ID, c.Customer_Name, c.Customer_Address, c.Customer_Category, c.Customer_Discount, o.Order_ID, o.Order_Date, o.Order_Total_Amount
  2  FROM Customer c
  3  JOIN Orders o ON c.Customer_ID = o.Customer_ID;

CUSTOMER_ID CUSTOMER_NAME        CUSTOMER_ADDRESS               CUSTOMER_CATEGO CUSTOMER_DISCOUNT   ORDER_ID ORDER_DAT ORDER_TOTAL_AMOUNT                                                                                                                                                                                                                                                                                                                                                                           
----------- -------------------- ------------------------------ --------------- ----------------- ---------- --------- ------------------                                                                                                                                                                                                                                                                                                                                                                           
          1 Rita Thakur          Bhaktapur                      Regular                         0          1 10-MAY-23                 30                                                                                                                                                                                                                                                                                                                                                                           
          2 Suman Khatri         Lalitpur                       Staff                           5          2 15-MAY-23                 40                                                                                                                                                                                                                                                                                                                                                                           
          3 Amit Sharma          Kathmandu                      Regular                         0          3 20-MAY-23                 50                                                                                                                                                                                                                                                                                                                                                                           
          4 Anju Shakya          Butwal                         Staff                           5          4 01-JUN-23                 60                                                                                                                                                                                                                                                                                                                                                                           
          5 Rajiv Koirala        Pokhara                        Vip                            10          5 05-JUN-23                 70                                                                                                                                                                                                                                                                                                                                                                           
          6 Neetu Gupta          Kathmandu                      Regular                         0          6 01-AUG-23                 80                                                                                                                                                                                                                                                                                                                                                                           
          7 Manish Thapa         Biratnagar                     Staff                           5          7 05-AUG-23                 90                                                                                                                                                                                                                                                                                                                                                                           

7 rows selected.

SQL> 
SQL> 
SQL> select * from customer
  2  where customer_id Not in (select c.customer_id from Customer c
  3  JOIN Orders o ON c.Customer_ID = o.Customer_ID);

CUSTOMER_ID CUSTOMER_NAME        CUSTOMER_ADDRESS               CUSTOMER_CATEGO CUSTOMER_DISCOUNT                                                                                                                                                                                                                                                                                                                                                                                                                   
----------- -------------------- ------------------------------ --------------- -----------------                                                                                                                                                                                                                                                                                                                                                                                                                   
          8 Riya Acharya         soltimood                      Vip                            10                                                                                                                                                                                                                                                                                                                                                                                                                   
          9 Sujan Khatri         Lalitpur                       Staff                           5                                                                                                                                                                                                                                                                                                                                                                                                                   

SQL> spool off
