SQL> SELECT *
  2  FROM Orders
  3  WHERE Order_Date BETWEEN TO_DATE('2023-05-01', 'YYYY-MM-DD') AND TO_DATE('2023-05-28', 'YYYY-MM-DD');

  ORDER_ID ORDER_DAT ORDER_TOTAL_AMOUNT PAYMENT_ID CUSTOMER_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                      
---------- --------- ------------------ ---------- -----------                                                                                                                                                                                                                                                                                                                                                                                                                                                      
         1 10-MAY-23                 30          1           1                                                                                                                                                                                                                                                                                                                                                                                                                                                      
         2 15-MAY-23                 40          2           2                                                                                                                                                                                                                                                                                                                                                                                                                                                      
         3 20-MAY-23                 50          1           3                                                                                                                                                                                                                                                                                                                                                                                                                                                      

SQL> spool off
