SQL> SELECT *
  2  FROM Customer
  3  WHERE Customer_Category = 'Staff';

CUSTOMER_ID CUSTOMER_NAME        CUSTOMER_ADDRESS               CUSTOMER_CATEGO CUSTOMER_DISCOUNT                                                                                                                                                                                                                                                                                                                                                                                                                   
----------- -------------------- ------------------------------ --------------- -----------------                                                                                                                                                                                                                                                                                                                                                                                                                   
          2 Suman Khatri         Lalitpur                       Staff                           5                                                                                                                                                                                                                                                                                                                                                                                                                   
          4 Anju Shakya          Butwal                         Staff                           5                                                                                                                                                                                                                                                                                                                                                                                                                   
          7 Manish Thapa         Biratnagar                     Staff                           5                                                                                                                                                                                                                                                                                                                                                                                                                   
          9 Sujan Khatri         Lalitpur                       Staff                           5                                                                                                                                                                                                                                                                                                                                                                                                                   

SQL> spool off
